apiVersion: v1
kind: Service
metadata:
  name: playhub-db
  labels:
    app: playhub-postgres
spec:
  type: ClusterIP
  selector:
    app: playhub-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
