apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playhub-postgres-data
  labels:
    app: playhub-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
